imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  # Controller
  cdigruttola\Bocustomize\Controller\BoCustomizeController:
    public: true
    class: cdigruttola\Bocustomize\Controller\BoCustomizeController
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages(false)"

  cdigruttola.bocustomize.form.configuration_type.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@cdigruttola.bocustomize.configuration.form_provider'
      - 'cdigruttola\Bocustomize\Form\BoCustomizeConfigurationType'
      - 'ConfigurationForm'

  cdigruttola.bocustomize.configuration.form_provider:
    class: cdigruttola\Bocustomize\Form\Provider\BoCustomizerConfigurationFormDataProvider
    arguments:
      - '@cdigruttola.bocustomize.configuration'

  cdigruttola.bocustomize.configuration:
    class: cdigruttola\Bocustomize\Form\DataConfiguration\BoCustomizeConfigurationData
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@cdigruttola.bocustomize.module'

  cdigruttola.bocustomize.form.configuration_type:
    class: cdigruttola\Bocustomize\Form\BoCustomizeConfigurationType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
